import { normalizeConfidence } from './newsDetector.js';
import API_BASE from '../config';

export async function analyzeImage(file, base64, apiKey) {
  // First, get dimensions and size for fallback/rule-based just in case
  const w = 0, h = 0; // Or keep the getImageDimensions logic if you want

  try {
    const response = await fetch(`${API_BASE}/api/analyze-image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ base64: base64, mimeType: file.type })
    });

    if (response.ok) {
      const data = await response.json();
      return {
        verdict: data.verdict,
        confidence: data.confidence,
        explanation: data.explanation,
        data_points: data.data_points,
        customTitle: data.customTitle,
        adult_content: data.adult_content,
        fake_content: data.fake_content,
        engine: data.engine
      };
    }
  } catch (err) {
    console.error("Server API failed, falling back to basic analysis", err);
  }

  // Fallback rule-based analysis (if API fails or key is missing)
  const AI_DIMENSIONS = [256, 512, 768, 1024, 1280, 1536, 2048];
  const AI_FILENAME = /midjourney|dall[._-]?e|stable[._-]?diff|dreamstudio|artbreeder|nightcafe|bluewillow|leonardo|bing[._-]?image|firefly|runway/i;
  
  const flags = [];
  const reasons = [];
  let rawScore = 0;

  if (AI_FILENAME.test(file.name)) {
    rawScore += 55; flags.push('AI tool name in filename');
    reasons.push(`The filename "${file.name}" contains a known AI image generator name`);
  }
  
  const sizeMB = file.size / 1_048_576;
  if (sizeMB < 0.25 && file.type === 'image/png') {
    rawScore += 20; flags.push('Suspiciously small PNG');
    reasons.push(`The file is only ${(sizeMB * 1024).toFixed(0)}KB — AI images often compress unnaturally well`);
  }
  
  if (/^\d{13,}|img_\d{4,}_\d|[a-f0-9]{8,}-[a-f0-9]{4}/i.test(file.name)) {
    rawScore += 12; flags.push('Auto-generated filename pattern');
    reasons.push('The filename looks auto-generated (random numbers/characters) — typical of AI image tools');
  }
  
  if (file.type === 'image/webp') {
    rawScore += 8; flags.push('WebP format');
    reasons.push('WebP format is commonly used by AI image generation tools and web-based AI art platforms');
  }

  if (reasons.length === 0) {
    reasons.push(
      'No AI tool name detected in the filename',
      'File size and format appear consistent with a real photograph'
    );
  }

  const verdict = rawScore > 44 ? 'FAKE' : 'REAL';
  const confidence = normalizeConfidence(verdict, Math.min(99, rawScore));

  const isFake = verdict === 'FAKE';

  return {
    verdict,
    confidence,
    explanation: isFake ? 'AI-generation signals detected based on file metadata.' : 'No AI-generation signals detected based on file metadata.',
    riskFlags: flags.length ? flags : ['No obvious AI-generation markers found'],
    customTitle: isFake ? 'Generated by AI' : 'Generated by Human!',
    adult_content: false,
    fake_content: isFake,
    engine: 'rule-based',
  };
}
